blank_issues_enabled: true
contact_links:
  - name: Alpha Support
    url: https://t.me/AlphaSupport
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://Alpha.tech/
    about: Documentation for getting started with bot.
